### ISSUE TITLE
How to set up assignee-to-reviewer-action as GitHub new workflow format?

### ISSUE THREAD

**Issue by kompiro** [pullreminders/assignee-to-reviewer-action#7]
I'd like to setup assignee-to-reviewer-action as new yaml format. (CI/CD support version)

```yaml
name: Assignee to Reviewer
on: pull_request

jobs:
  assignee_to_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Assignee to Reviewer
        uses: pullreminders/assignee-to-reviewer-action@v1.0.4
```

I got error with exit code 78.

```
##[error]Docker run failed with exit code 78
```

Please add an example to use assignee-to-reviewer-action on new yaml format.
